=== Ippokratis-Kotsanis/M.Sc.-DWS-Semantic-Web/Assignment-XML-XSLT-131/131/131_ΕΡΓΑΣΙΑ1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ENTITY AUTHOR "Ippokratis kotsanis">
<!ENTITY COMPANY "Dataverse LTD">

<!ELEMENT COMPANY (DEPARTMENT,EQUIPMENT)>
<!ELEMENT DEPARTMENT (D_NAME,PROJECT+)>
<!ELEMENT D_NAME (#PCDATA)>
<!ATTLIST DEPARTMENT
	id ID #REQUIRED
	COUNTRY (GREECE|SLOVAKIA|NORWAY) "GREECE">

<!ELEMENT PROJECT (TEAM+,EMPLOYEE+)>
<!ATTLIST PROJECT
	id_PROJ ID #REQUIRED
	NAME CDATA #REQUIRED
	EMPLOYEES_NO CDATA #REQUIRED
	TEAMS_NO CDATA #IMPLIED
	DEPARTMENT_NO CDATA #IMPLIED>

<!ELEMENT TEAM (FULLSTACK+,FRONTEND,BACKEND)>
<!ATTLIST TEAM
	id_TEAM ID #REQUIRED
	NAME CDATA #REQUIRED>

<!ELEMENT FULLSTACK (NAME_FS,ID_TEAMFS)>
<!ELEMENT NAME_FS (#PCDATA)>
<!ELEMENT ID_TEAMFS (#PCDATA)>

<!ELEMENT FRONTEND (NAME_FE,ID_TEAMFE)>
<!ELEMENT NAME_FE (#PCDATA)>
<!ELEMENT ID_TEAMFE (#PCDATA)>

<!ELEMENT BACKEND (NAME_BE,ID_TEAMBE)>
<!ELEMENT NAME_BE (#PCDATA)>
<!ELEMENT ID_TEAMBE (#PCDATA)>

<!ELEMENT EMPLOYEE (DEVELOPER,QA,TEAM_LEADER)>
<!ELEMENT DEVELOPER (#PCDATA)>
<!ATTLIST DEVELOPER
	id ID #REQUIRED
	TEAM_ID IDREF #IMPLIED
	LEVEL_TYPE CDATA #REQUIRED
	SALARY CDATA #REQUIRED
	NUMBER_D CDATA #REQUIRED>

<!ELEMENT QA (#PCDATA)>
<!ATTLIST QA 
	id ID #REQUIRED
	TEAM_ID IDREF #IMPLIED
	LEVEL_TYPE CDATA #REQUIRED
	SALARY CDATA #REQUIRED
	NUMBER_QA CDATA #REQUIRED>

<!ELEMENT TEAM_LEADER (#PCDATA)>
<!ATTLIST TEAM_LEADER 
	id ID #REQUIRED
	TEAM_ID IDREF #IMPLIED
	LEVEL_TYPE (SENIOR|MID|JUNIOR) "SENIOR"
	SALARY CDATA #REQUIRED
	NUMBER_TL CDATA #REQUIRED>	

<!ELEMENT EQUIPMENT (LAPTOP+,DESK+,PRINTER+)>

<!ELEMENT LAPTOP (NAME_LAPTOP)>
<!ATTLIST LAPTOP
	id_laptop ID #REQUIRED
	CPU CDATA #REQUIRED
	RAM CDATA #REQUIRED
	ROM CDATA #REQUIRED>
<!ELEMENT NAME_LAPTOP (#PCDATA)>

<!ELEMENT DESK (CHAIR)>
<!ELEMENT CHAIR EMPTY>
<!ATTLIST CHAIR
	CHAIR_NO CDATA #REQUIRED
	COLOUR (BLACK|BROWN|WHITE) "BLACK"
	TYPE (OLD|NEW) "NEW">
	
<!ELEMENT PRINTER (NAME_PRINTER)>
<!ATTLIST PRINTER
	ID_PRINTER ID #REQUIRED
	MODEL CDATA #REQUIRED
	TYPE (BW|COLOUR) "COLOUR">
<!ELEMENT NAME_PRINTER (#PCDATA)>

=== Ippokratis-Kotsanis/M.Sc.-DWS-Semantic-Web/Assignment-XML-XSLT-131/131/131_ΕΡΓΑΣΙΑ1_XML.xml
<?xml version="1.1" encoding="UTF-8"?>
<!DOCTYPE COMPANY SYSTEM "C:\Users\user\Documents\Altova\XMLSpy2023\Examples\131_ΕΡΓΑΣΙΑ1.dtd">
<COMPANY>
	<DEPARTMENT id="ID1">
		<D_NAME>GREECE DEPARTMENT</D_NAME>
		<PROJECT NAME="Admincontrol" id_PROJ="ID456557" EMPLOYEES_NO="120">
			<TEAM NAME="Admincontrol team" id_TEAM="ID3">
				<FULLSTACK>
					<NAME_FS>Tornado team</NAME_FS>
					<ID_TEAMFS>ID101</ID_TEAMFS>
				</FULLSTACK>
				<FRONTEND>
					<NAME_FE>Angular team</NAME_FE>
					<ID_TEAMFE>ID201</ID_TEAMFE>
				</FRONTEND>
				<BACKEND>
					<NAME_BE>Platform team</NAME_BE>
					<ID_TEAMBE>ID301</ID_TEAMBE>
				</BACKEND>
			</TEAM>
			<EMPLOYEE>
				<DEVELOPER id="IDeveloper456557" SALARY="1500E" LEVEL_TYPE="SENIOR" NUMBER_D="86">Project Admincontrol
				 has 86 senior developers higly skilled in web development. Their main responsibilities
				 are feature implementation and bug fixing.</DEVELOPER>
				<QA id="IDQA456557" SALARY="1200E" LEVEL_TYPE="MID" NUMBER_QA="31">Project Admincontrol has 31 QA senior tester, who run tests in selenium programm.</QA>
				<TEAM_LEADER id="IDTeamLeader456557" SALARY="2000E" LEVEL_TYPE="SENIOR" NUMBER_TL="3">Team leaders in Admincontrol
				 are responsible to organize their teams. There are 3 team leaders in Admincontrol project.</TEAM_LEADER>
			</EMPLOYEE>
		</PROJECT>
	</DEPARTMENT>
	<EQUIPMENT>
		<LAPTOP CPU="I5 10Gen" RAM="16 GB" ROM="1 TB ssd" id_laptop="IDA456557">
			<NAME_LAPTOP>Dell Inspiron A8562</NAME_LAPTOP>
		</LAPTOP>
		<DESK>
			<CHAIR CHAIR_NO="150" COLOUR="BLACK" TYPE="NEW"></CHAIR>
		</DESK>
		<PRINTER MODEL="HP LASERJET SF-760P" ID_PRINTER="IDPrinter456557">
			<NAME_PRINTER>HP Admincontrol printer</NAME_PRINTER>
		</PRINTER>
	</EQUIPMENT>
</COMPANY>
